### ISSUE TITLE
Part of the code for soft prompt optimization seems to be missing

### ISSUE THREAD

**Issue by Iriseve** [czx-li/Concentrate-Attention#1]
Thanks for your work, but the code for soft prompt optimization doesn't seem to be complete. 
**Both `Prompt-Tune-Other.py` and `Prompt-Tune.py` use the code `import model as M` and `model = M.RobertaPromptTune(...)`, but the `model.py` file seems to be missing.**
Could you please add that? Thank you very much:)

**Comment by czx-li** [comment]
Thank you very much for your recognition of this work. We apologize for the messiness caused by multiple iterations of the code. We will update the missing content as soon as possible.

**Comment by czx-li** [comment]
> Thanks for your work, but the code for soft prompt optimization doesn't seem to be complete. **Both `Prompt-Tune-Other.py` and `Prompt-Tune.py` use the code `import model as M` and `model = M.RobertaPromptTune(...)`, but the `model.py` file seems to be missing.** Could you please add that? Thank you very much:)

Thank you very much for your recognition of this work. We apologize for the messiness caused by multiple iterations of the code. We will update the missing content as soon as possible.
